services:
  db:
    image: mysql:8.0
    container_name: mysql-database
    restart: always
    environment:
      MYSQL_DATABASE: game_management
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD-SHELL", "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'SELECT 1;'"]
        interval: 10s       # Kiểm tra mỗi 10 giây
        timeout: 5s        # Chờ phản hồi trong 5 giây
        retries: 10        # Thử lại 10 lần
        start_period: 30s
  app:
    build: .
    container_name: game-app-container
    ports:
      - "8888:8080"
    depends_on:
      - db